[project]
name = "fantasy-football-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "bs4>=0.0.2",
    "dbt-postgres>=1.10.0",
    "pandas>=3.0.2",
    "psycopg2-binary>=2.9.12",
    "requests>=2.33.1",
    "soccerdata>=1.9.0",
    "sqlalchemy>=2.0.50",
    "tdqm>=0.0.1",
    "tqdm>=4.67.3",
]
